### ISSUE TITLE
Expose OMEGA_H_USE_YAML to users via CMake

### ISSUE THREAD

**Issue by bgranzow** [ibaned/omega_h#170]
I am building Omega_h with most (all?) Trilinos options enabled (Kokkos, TeuchosComm, TeuchosParameterList) and linking an application to Omega_h and all other dependencies via CMake with
```
target_link_libraries(target_name Omega_h::omega_h)
```
To check that Omega_h was actually compiled with Kokkos, for instance, I do the following in my application's CMakeLists.txt
```
if(NOT "Kokkos" IN_LIST Omega_h_DEPS)
  message(FATAL_ERROR "Omega_h must be compiled with Kokkos enabled")
endif()
```
Would it be possible to export some similar information via CMake about whether or not it was compiled to use YAML with Teuchos?

**Comment by ibaned** [comment]
Yea, this is something I have trouble getting out of Trilinos as well. I'll try adding something to `bob.cmake` that will export a given set of CMake variables into the `PackageConfig.cmake` file.

**Comment by ibaned** [comment]
I just added this via ibaned/cmake_bob@e617a6e.
Please read that commit message for the other cool new things it enables.
You should get `Omega_h_USE_Kokkos` from `Omega_hConfig.cmake`, among other things.

Note this is all in the `develop` branch !
I really must finish the Alexa CDash refactor next week, at which point there will be a long-awaited develop->master merge.

**Comment by ibaned** [comment]
Hmm this is technically not done because it doesn't include `Omega_h_USE_YAML`, which is not a CMake variable yet. Reopening until that detail gets covered.

**Comment by ibaned** [comment]
#172 will cover the remaining piece of this

**Comment by ibaned** [comment]
With 99e7036 in develop, `Omega_h_USE_YAML` will show up via `Omega_hConfig.cmake` to downstream users. There is also `Omega_h_USE_KokkosCore` and `Omega_h_USE_TeuchosParameterList`.

The develop->master merge will likely happen tomorrow, since the Alexa dashboard is up and running.

**Comment by bgranzow** [comment]
Thank you!
