### ISSUE TITLE
Access mesh quality stuff through python

### ISSUE THREAD

**Issue by bonh** [ibaned/omega_h#214]

**Comment by ibaned** [comment]
@bonh I just released version 9.11.0 of Omega_h, which includes the following:
```python
minq = mesh.min_quality() #uses "mean ratio" formula, 0.3 and up are considered "good"
maxl = mesh.max_length() #this means maximum (edge length relative to desired length)
```

I'll close this for now, please comment if something doesn't work.
Thanks!

**Comment by bonh** [comment]
@ibaned It works and it is helpful for sure - but can you add a method to write the local quality value to a vtk file?

**Comment by ibaned** [comment]
@bonh this should already happen if you do:
```python
PyOmega_h.vtk_write_vtu("foo.vtu", mesh)
```
