### ISSUE TITLE
usage of your software

### ISSUE THREAD

**Issue by tcaduser** [ibaned/omega_h#218]
Hello,

I was wondering if your tool works from both
1. geometric boundary representations
2. an existing 3d mesh

Is your software capable of:
1. Interpolating vertex data on the new mesh
2. Automatically identifying surfaces between regions.

Do you have any additional documentation, other than what is in the doc directory?

**Comment by ibaned** [comment]
Hi @tcaduser !
Currently Omega_h works with existing 3D meshes. For non-trivial geometric boundary representations, it is recommended to first run a 3D tet mesh generator. Gmsh is a good open-source one, Omega_h can read its output files. If you choose a generator whose format we don't yet support, I'd be happy to add a reader for said format.

Omega_h can interpolate vertex data onto the new mesh.

Surfaces will either be known _a priori_ if the mesh comes from a good source like Gmsh (and they will remain tracked as the mesh is modified), or we also have mechanisms for marking surfaces and curves when given only knowledge of which elements are in which region.

Unfortunately documentation continues to be lacking, but I do my best to answer user's queries and will try to create more documentation as resources allow.

**Comment by tcaduser** [comment]
Thank you
