### ISSUE TITLE
‘element_size’ was not declared in this scope during build

### ISSUE THREAD

**Issue by bonh** [ibaned/omega_h#233]
Docker:
`quay.io/fenicsproject/stable:latest`

CMake:
`cmake $HOME/omega_h -DCMAKE_INSTALL_PREFIX:PATH=$HOME/omega_h/install -DCMAKE_CXX_COMPILER:FILEPATH="which mpicxx" -DCMAKE_C_COMPILER:FILEPATH="which mpicc" -DBUILD_SHARED_LIBS:BOOL=ON -DOmega_h_USE_MPI:BOOL=ON -DOmega_h_USE_ZLIB:BOOL=ON -DOmega_h_USE_DOLFIN:BOOL=ON -DDOLFIN_SKIP_BUILD_TESTS=OF`

Error:
`/home/fenics/omega_h/src/Omega_h_dolfin.cpp: In instantiation of ‘Omega_h::fix_inverted_elements_dim(Omega_h::Write<int>, Omega_h::Reals)::<lambda(Omega_h::LO)> [with int dim = 1; Omega_h::LO = int]’:
/home/fenics/omega_h/src/Omega_h_dolfin.cpp:157:55:   required from ‘struct Omega_h::fix_inverted_elements_dim(Omega_h::Write<int>, Omega_h::Reals) [with int dim = 1]::<lambda(Omega_h::LO)>’
/home/fenics/omega_h/src/Omega_h_dolfin.cpp:164:3:   required from ‘void Omega_h::fix_inverted_elements_dim(Omega_h::Write<int>, Omega_h::Reals) [with int dim = 1]’
/home/fenics/omega_h/src/Omega_h_dolfin.cpp:169:64:   required from here
/home/fenics/omega_h/src/Omega_h_dolfin.cpp:159:26: error: ‘element_size’ was not declared in this scope
     auto s = element_size(b);`

**Comment by ibaned** [comment]
Thanks for reporting this @bonh !
I just pushed a fix in release `v9.13.6`.
I'll try to check the FEniCS interface before pushing future releases.

**Comment by bonh** [comment]
works, thx!
