### ISSUE TITLE
zlib fails to link with -DUSE_XSDK_DEFAULTS:BOOL=true

### ISSUE THREAD

**Issue by jbakosi** [ibaned/omega_h#238]
Trying to build as
```
cmake -GNinja -DOmega_h_USE_MPI=true -DCMAKE_CXX_COMPILER=mpicxx -DUSE_XSDK_DEFAULTS:BOOL=true ..
```
results in
```
[105/116] Linking CXX executable src/osh2vtk
FAILED: src/osh2vtk 
: && /opt/openmpi/2.0.2/clang/system/bin/mpicxx  -g  -rdynamic src/CMakeFiles/osh2vtk.dir/osh2vtk.cpp.o  -o src/osh2vtk  -Wl,-rpath,/home/jbakosi/code/etc/thirdparty/omega_h/build/src: src/libomega_h.so && :
/usr/bin/ld: src/libomega_h.so: undefined reference to `uncompress'
/usr/bin/ld: src/libomega_h.so: undefined reference to `compress2'
/usr/bin/ld: src/libomega_h.so: undefined reference to `compressBound'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[106/116] Linking CXX executable src/msh2osh
FAILED: src/msh2osh 
```

and so on for all executables. The problem goes away if` -DUSE_XSDK_DEFAULTS:BOOL=false` .

**Comment by ibaned** [comment]
Unfortunately, xSDK chose to require a standard set of CMake options where users have to set:
```
-DTPL_ENABLE_ZLib=YES
-DTPL_ZLib_LIBRARIES="/path/to/libz.so"
```
And so on...

**Comment by ibaned** [comment]
https://figshare.com/articles/xSDK_Community_Installation_Policies_GNU_Autoconf_and_CMake_Options/4495133

**Comment by jbakosi** [comment]
I'm not sure if I understand their motivation in that policy document. A library, e.g., Omega_h, cannot choose to detect its TPLs but must require the user to provide an explicit path and library name? Besides that not being portable and that cmake doing a lot of that correctly on many platforms already, if that is so, that eases the job of the "integrator" but the developer and definitely not the user. Seems pretty irrational.

**Comment by ibaned** [comment]
I agree @jbakosi, it is only slightly alleviated by xSDK's use of Spack, which finds the paths and library names of TPLs for you. Still, it is likely that the xSDK mode is not well suited for your needs due to their choices. I can add a third option in Omega_h to just accept `CMAKE_BUILD_TYPE` without also bringing in the rest of xSDK's decisions. I'll comment here when thats done.

**Comment by jbakosi** [comment]
Yeah, I guess the xSDK folks want to make their own life easier by requiring to some sensible defaults to xSDK-compliant packages that they can rely on for integration - that's cool and understandable.

@ibaned don't worry about adding `CMAKE_BUILD_TYPE`, we will just use the non-xSDK defaults of Omega_h: https://github.com/quinoacomputing/quinoa-tpl/commit/4c25e41d497af5c19e64cbbe2a22cf057a563c50.
