### ISSUE TITLE
Difficulties to refine the mesh of an elongated geometry

### ISSUE THREAD

**Issue by smelchio** [ibaned/omega_h#243]
In the following code, modifying the last argument of get_metric_scalar_for_nelems does not give a finer mesh. Could you help finding the right parameters or functions to refine isotropically everywhere?

```cpp
#include "Omega_h_adapt.hpp"
#include "Omega_h_metric.hpp"
#include "Omega_h_array_ops.hpp"
#include "Omega_h_build.hpp"

#include <cstdlib>
#include <iostream>

int main(int argc, char** argv) {
  auto lib = Omega_h::Library(&argc, &argv);
  auto mesh = Omega_h::build_box(lib.world(), OMEGA_H_SIMPLEX, 1e-6, 1e-6, 1e-3, 4, 4, 100);
  mesh.set_parting(OMEGA_H_GHOSTED);
  auto metrics = Omega_h::get_implied_isos(&mesh);
  auto scalar = Omega_h::get_metric_scalar_for_nelems(&mesh, metrics, 100000);
  metrics = multiply_each_by(metrics, scalar);
  mesh.add_tag(Omega_h::VERT, "metric", 1, metrics);
  auto opts = Omega_h::AdaptOpts(&mesh);
  opts.min_quality_allowed = 0.0017;
  opts.max_length_desired = 2.8;
  opts.verbosity = Omega_h::EXTRA_STATS;
  Omega_h::adapt(&mesh, opts);
  mesh.remove_tag(Omega_h::VERT, "metric");
}
```

**Comment by ibaned** [comment]
Well, for starters, I don't think the initial mesh is isotropic. The XY resolution is `1e-6/4 = 2.5e-7` and the Z resolution is `1e-3/100=1e-5`, so there is an aspect ratio of `2.5e-7:1e-5 = 1:40`. So, it doesn't make sense to use isotropic features like `get_implied_isos`. As a general rule: if you have to modify `min_quality_allowed`, you're probably specifying some other inputs wrong. I'll also throw in the enhancement that it is better to "approach" large changes in a metric. Here is a code which generated an (anisotropic) mesh of about 103K elements for me (in serial):
```cpp
#include "Omega_h_adapt.hpp"
#include "Omega_h_metric.hpp"
#include "Omega_h_array_ops.hpp"
#include "Omega_h_build.hpp"
#include "Omega_h_file.hpp"

#include <cstdlib>
#include <iostream>

int main(int argc, char** argv) {
  auto lib = Omega_h::Library(&argc, &argv);
  auto mesh = Omega_h::build_box(lib.world(), OMEGA_H_SIMPLEX, 1e-6, 1e-6, 1e-3, 4, 4, 100);
  mesh.set_parting(OMEGA_H_GHOSTED);
  Omega_h::add_implied_metric_tag(&mesh);
  auto metrics = mesh.get_array<double>(0, "metric");
  auto scalar = Omega_h::get_metric_scalar_for_nelems(&mesh, metrics, 100000);
  std::cout << "scalar was " << scalar << '\n';
  metrics = multiply_each_by(metrics, scalar);
  mesh.add_tag(Omega_h::VERT, "target_metric", Omega_h::symm_ncomps(mesh.dim()), metrics);
  auto opts = Omega_h::AdaptOpts(&mesh);
  opts.verbosity = Omega_h::EXTRA_STATS;
  while (Omega_h::approach_metric(&mesh, opts)) {
    Omega_h::adapt(&mesh, opts);
  }
  Omega_h::vtk::write_vtu("out.vtu", &mesh);
}
```
If you change the box parameters to actually generate an isotropic initial mesh then you can go back to using the isotropic metric functions.

**Comment by smelchio** [comment]
Thanks a lot. I agree that the mesh was not isotropic. I will try this out and close the issue if I am able use your suggestion for my purpose.

**Comment by smelchio** [comment]
I tried your code below. If I keep target_nelems = 100000 I get 103011 test if I use p = 1, 2 or 4 procs but I observed that the time for the refinement is O(p). If I choose instead target_nelems=10*mesh.nelems()*16 ~= 1.5e6, I do not have the same number of tets depending on p, i.e., 1.1e6 tets if I uses 1 task but only 0.7e6 tets if I uses 2 tasks and this number keep reducing for larger p. Could you please explain if I am doing something wrong? Many thanks.

**Comment by ibaned** [comment]
Okay, there are two issues here:
1. The O(p) runtime. This usually indicates that load balance is not good. Maybe try calling `mesh.balance()` after `build_box`?
2. The reason `mesh.nelems()` doesn't work is that it only counts the elements in the local MPI rank. Please use `mesh.nglobal_ents(mesh.dim())` to compute the total number of elements across all MPI ranks. This is a collective communication operation (`MPI_Allreduce`).

**Comment by smelchio** [comment]
Thanks a lot; now you said it, the second issue is really obvious. I tried it out but mesh.balance() does not fix the scaling issue. Would you have another suggestion, please?

**Comment by ibaned** [comment]
I don't really have another suggestion besides that... if you continue to see O(p) times for higher data points (more than 4 ranks, closer to millions of elements), then I can spend some time optimizing the code.

**Comment by smelchio** [comment]
I could not get better scaling today. Could you please tell us how can we further proceed? Many thanks !

**Comment by ibaned** [comment]
For more than 4 procs and/or more than 100K elements?

**Comment by smelchio** [comment]
My current investigations on strong scaling with 5.5e6 tets in total and 64 tasks per node:

On 2 nodes: mesh refinement = 82s, ~4.8e4 tets per proc
On 4 nodes: mesh refinement = 77s, ~2.4e4 tets per proc
On 8 nodes: mesh refinement = 89s, ~1.2e4 tets per proc

I also have similar observations for weak scaling investigations

**Comment by smelchio** [comment]
```
            mesh = Omega_h::build_box(world, OMEGA_H_SIMPLEX, 1e-6, 1e-6, 1e-3, 7, 7, 210);
            mesh.balance();
            mesh.set_parting(OMEGA_H_GHOSTED);
            Omega_h::add_implied_metric_tag(&mesh);
            auto metrics = mesh.get_array<double>(0, "metric");
            auto scalar = Omega_h::get_metric_scalar_for_nelems(&mesh, metrics, mesh.nglobal_ents(mesh.dim())*100);
            metrics = multiply_each_by(metrics, scalar);
            mesh.add_tag(Omega_h::VERT, "target_metric", Omega_h::symm_ncomps(mesh.dim()), metrics);
            auto opts = Omega_h::AdaptOpts(&mesh);
            opts.verbosity = Omega_h::SILENT;//EXTRA_STATS;
            while (Omega_h::approach_metric(&mesh, opts)) {
                Omega_h::adapt(&mesh, opts);
            }
```

**Comment by smelchio** [comment]
I pushed further the investigation and it starts getting better with ~2.5e5 tets per proc and 32 tasks/n:
On 1 node: mesh refinement = 216s, ksp-solver = 60s, ~8.4e6 tets in total
On 2 nodes: mesh refinement = 270s, ksp-solver = 52s, ~1.4e7 tets in total
On 4 nodes: mesh refinement = 397s, ksp-solver = 97s, ~2.9e7 tets in total
On 8 nodes: mesh refinement = 355s, ksp-solver = 27s, ~4.9e7 tets in total
On 16 nodes: mesh refinement = 523s, ksp-solver = ???s, ~9.5e7 tets in total

**Comment by smelchio** [comment]
I pushed further again with ~7e5 tets per proc and 32 tasks/n:
On 1 node: mesh refinement = 260s, ksp-solver = 197s, ~2.3e7 tets in total
On 2 nodes: mesh refinement = 317s, ksp-solver = 177s, ~4.6e7 tets in total
On 4 nodes: mesh refinement = 442s, ksp-solver = 198s, ~7.9e7 tets in total
On 8 nodes: mesh refinement = 667s, ksp-solver = ???s, ~1.9e8 tets in total

**Comment by smelchio** [comment]
Further strong scaling still running with ~1.5e6 tets per proc and still 32 task per node:
On 1 node: mesh refinement = 1116s, ksp-solver - ???s, ~4.5e7 test in total

**Comment by smelchio** [comment]
Weak scaling on coarser mesh, i.e. ~1.8e5 tets per proc, 32 tasks/n:
On 1 node: mesh refinement = 121s, ksp-solver = 63s, ~5.7e6 tets in total
On 2 nodes: mesh refinement = 205s, ksp-solver = 81s, ~1.1e7 tets in total
On 4 nodes: mesh refinement = 394s, ksp-solver = 180s, ~1.8e7 tets in total

Note that we intend to run a profiler to get a bit more insight. In the meantime, would you have any comment?

**Comment by ibaned** [comment]
I think profiling is the right next step here. The crash is also concerning but its likely to be an MPI bug. For profiling, I think you should be able to run the code with the command line option `--osh-time`, assuming you're building the `Omega_h::Library` object using the command line arguments. That should give you some profiling output of the functions inside Omega_h. Please let me know if you have trouble using that option.

**Comment by smelchio** [comment]
Thanks for the suggestions. We have some delay in running the profiling but in the meantime we got the following results that were waiting in the queue:
Weak scaling still running with ~2.5e6 tets per proc, 32 tasks/n:
On 1 node: mesh refinement = 2681s, ksp-solver - 679s, ~7.4e7 tets in total
On 2 nodes: mesh refinement = 4042s, ksp-solver - 1056s, ~1.4e8 tets in total
On 4 nodes: mesh refinement = 9102s, ksp-solver = ???s, ~2.9e8 tets in total
On 8 nodes: mesh refinement = 5717s, ksp-solver = 989s, ~3.5e8 tets in total
On 16 nodes: mesh refinement = 5689s, ksp-solver = ???s, ~7.1e8 tets in total

**Comment by ibaned** [comment]
So using this code:
```cpp
#include <Omega_h_build.hpp>
#include <Omega_h_adapt.hpp>
#include <Omega_h_metric.hpp>
#include <Omega_h_array_ops.hpp>
#include <Omega_h_stack.hpp>

#include <iostream>

int main(int argc, char** argv) {
  auto lib = Omega_h::Library(&argc, &argv);
  Omega_h::ScopedTimer scoped_timer("main");
  auto world = lib.world();
  if (world->rank() == 0) std::cout << "building a box of " << (6 * 7 * 7 * 210) << " elements!\n";
  auto mesh = Omega_h::build_box(world, OMEGA_H_SIMPLEX, 1e-6, 1e-6, 1e-3, 7, 7, 210);
  if (world->rank() == 0) std::cout << "done building the box, re-balancing!\n";
  mesh.balance();
  if (world->rank() == 0) std::cout << "done rebalancing, rank 0 has " << mesh.nelems() << " elements!\n";
  if (world->rank() == 0) std::cout << "ghosting!\n";
  mesh.set_parting(OMEGA_H_GHOSTED);
  if (world->rank() == 0) std::cout << "done ghosting, rank 0 has " << mesh.nelems() << " elements!\n";
  if (world->rank() == 0) std::cout << "computing implied metric!\n";
  Omega_h::add_implied_metric_tag(&mesh);
  auto ncurrent_elems = mesh.nglobal_ents(mesh.dim());
  auto ntarget_elems = ncurrent_elems * 8;
  if (world->rank() == 0) std::cout << "done with implied metric, scaling it to " << ntarget_elems << " elements!\n"; 
  auto metrics = mesh.get_array<double>(0, "metric");
  auto scalar = Omega_h::get_metric_scalar_for_nelems(mesh.dim(), ncurrent_elems, ntarget_elems);
  if (world->rank() == 0) std::cout << "scalar is " << scalar << "!\n";
  metrics = multiply_each_by(metrics, scalar);
  mesh.add_tag(Omega_h::VERT, "target_metric", Omega_h::symm_ncomps(mesh.dim()), metrics);
  auto opts = Omega_h::AdaptOpts(&mesh);
  opts.verbosity = Omega_h::EXTRA_STATS;
  if (world->rank() == 0) std::cout << "done scaling, adapting!\n";
  while (Omega_h::approach_metric(&mesh, opts)) {
      Omega_h::adapt(&mesh, opts);
  }
}
```
I actually get good scaling from 2 ranks (62 seconds) to 4 ranks (34 seconds).

**Comment by ibaned** [comment]
This may sound too trivial, but it is important to double-check that `Omega_h_USE_MPI=ON` in CMake...

**Comment by ibaned** [comment]
@smelchio @tristan0x with release `v9.22.2`, I've done some MPI scalability testing and changed a few of the internals to work around OpenMPI 2 bugs. Please see (this file)[https://github.com/ibaned/omega_h/blob/144a1c16b5f4c8dd66e55e8d43e9c37af0b5890b/src/refine_scale.cpp] for my latest attempt at a scalable mesh refinement function. I've tested this up to 64 ranks, and am trying to find an available machine with more cores.

**Comment by smelchio** [comment]
Thank you very much for providing us `v9.22.2` and your latest attempt at a scalable mesh refinement. The following strong scaling diagram confirm that the complexity scales as O(N/P log(P)) 
![image](https://user-images.githubusercontent.com/35073063/49385010-9e31aa00-f71c-11e8-9253-45832c20a305.png)

**Comment by ibaned** [comment]
I'm going to close this assuming that the main issue has been resolved, but please comment if there is more related to this specific issue of scalability.
