### ISSUE TITLE
Expose file I/O headers in install

### ISSUE THREAD

**Issue by bgranzow** [ibaned/omega_h#259]
Would it be OK to install
```
Omega_h_vtk.hpp
Omega_h_base64.hpp
Omega_h_xml_lite.hpp
```

so that I could write a custom vtk output class in a downstream application without having to re-implement these capabilities?

**Comment by ibaned** [comment]
Yep! pull request welcome!

**Comment by bgranzow** [comment]
Thanks, building/testing now.
