### ISSUE TITLE
omega-h-9.19.0 build error on fedora28 via spack

### ISSUE THREAD

**Issue by balay** [ibaned/omega_h#267]
I'm getting build errors  when instaling omega-h via spack for xsdk.

I've tried disabling trilinos option - and still get errors. Attaching both logs.

[omega-h-9.15.0-spack-build.out.txt](https://github.com/ibaned/omega_h/files/2474750/omega-h-9.15.0-spack-build.out.txt)
[omega-h-9.15.0-spack-build.out-notrilinos.txt](https://github.com/ibaned/omega_h/files/2474755/omega-h-9.15.0-spack-build.out-notrilinos.txt)

**Comment by balay** [comment]
Ah - I meant to use 9.19.0 - will recheck.

**Comment by balay** [comment]
attaching log with 9.19.0 
[omega-h-9.19.0-spack-build.out.txt](https://github.com/ibaned/omega_h/files/2474810/omega-h-9.19.0-spack-build.out.txt)

**Comment by ibaned** [comment]
@balay GCC 8 has a bug that prevents it from compiling Omega_h:

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=86610
