### ISSUE TITLE
Non-optimized build fails

### ISSUE THREAD

**Issue by bgranzow** [ibaned/omega_h#280]
Using the config script

```
#!/bin/bash -ex
cmake $HOME/src/omega_h \
-DBUILD_TESTING:BOOL=ON \
-DBUILD_SHARED_LIBS:BOOL=ON \
-DCMAKE_INSTALL_PREFIX:PATH=$HOME/install/omega_h \
-DCMAKE_CXX_COMPILER:FILEPATH=$HOME/install/mpich/bin/mpicxx \
-DOmega_h_USE_Trilinos:BOOL=OFF \
-DOmega_h_CHECK_BOUNDS:BOOL=ON \
-DOmega_h_CXX_OPTIMIZE:BOOL=OFF \
-DOmega_h_USE_MPI:BOOL=ON \
2>&1 | tee config_log
```

With clang 9.0.0:
compilation fails at link time with the error:

```
Undefined symbols for architecture x86_64:
  "Omega_h::HostRead<int>::HostRead()", referenced from:
      Omega_h::Comm::Comm() in Omega_h_comm.cpp.o
      Omega_h::Comm::Comm(Omega_h::Library*, int) in Omega_h_comm.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

With gcc 7.3.0:
compilation fails for a unit test with the error:

```
In file included from /gpfs1/bngranz/omega_h/src/Omega_h_array_ops.hpp:7:0,
                 from /gpfs1/bngranz/omega_h/src/unit_math.cpp:1:
/gpfs1/bngranz/omega_h/src/Omega_h_scalar.hpp: In function ‘Omega_h::Vector<n> Omega_h::get_size_gradient(Omega_h::Few<Omega_h::Vector<n>, (dim + 1)>, Omega_h::Int) [with int dim = 3]’:
/gpfs1/bngranz/omega_h/src/Omega_h_scalar.hpp:124:28: error: inlining failed in call to always_inline ‘constexpr T Omega_h::factorial(T) noexcept [with T = int]’: function not considered for inlining
 constexpr OMEGA_H_INLINE T factorial(T x) noexcept {
                            ^~~~~~~~~
/gpfs1/bngranz/omega_h/src/Omega_h_scalar.hpp:125:34: note: called from here
   return (x > 1) ? (x * factorial(x - 1)) : 1;
```

I understand the gcc error, but am unsure of what to do about it. The clang error is a mystery to me, HostRead is for sure ETI'd for ints.

**Comment by ibaned** [comment]
Clang on Mac works fine... To workaround the GCC one we'd probably have to have like `OMEGA_H_IS_OPTIMIZED` so that we can `#ifdef` based on that... Is there really any reason to ever turn off optimization? LLDB is able to show me all the inlined function calls even with optimization, so I don't think debugging is a valid reason anymore.

**Comment by bgranzow** [comment]
Clang on Mac was where I saw the first error. Maybe we have different clang versions. (clang-900.0.39.2)

I never personally turn optimize off, but Kevin wanted it for debugging purposes and asked me to open this issue.

**Comment by ibaned** [comment]
Yep I forgot I got a new Clang version:

Apple LLVM version 10.0.0 (clang-1000.11.45.5)

**Comment by ibaned** [comment]
I'll accept PRs to fix this, but I won't spend time on it myself since I don't think you need `-O0` to debug.

**Comment by bgranzow** [comment]
Welp, I'm too dumb to fix it, so I'm just gonna close it and say the solution is to debug with a newer clang version.
