### ISSUE TITLE
MPI overlapping memcpy error

### ISSUE THREAD

**Issue by tamaradanceva** [ibaned/omega_h#285]
Hi, I have the following problem using MPI, resulting from adapt and other parallel operations. At first I though that this is specific to my case with FEniCS, since the compilation and installation goes well and the examples work as expected, however then I found the automated tests, some of which also make use of adapt. Using MPI and running the tests, results in:

> The following tests FAILED:
	  3 - run_unit_mesh (Failed)
	  4 - run_unit_io (Failed)
	  7 - run_mpi_tests (Failed)
	  8 - serial_1d_test (Failed)
	  9 - parallel_1d_test (Failed)
	 10 - run_corner_test (Failed)
	 11 - run_coarsen_test (Failed)
	 12 - serial_2d_conserve (Failed)
	 13 - parallel_2d_conserve (Failed)
	 14 - warp_test_serial (Failed)
	 15 - warp_test_parallel (Failed)
	 16 - run_aniso_test (Failed)
	 18 - amr_test (Failed)
	 19 - amr_test2 (Failed)
Errors while running CTest
Makefile:118: recipe for target 'test' failed
make: *** [test] Error 8

More specifically, running the tests, the error is:

Assertion failed in file src/mpid/ch3/src/ch3u_buffer.c at line 77: FALSE
memcpy argument memory ranges overlap, dst_=0x7ffd46d10abf src_=0x7ffd46d10abf len_=1

I looked over the issues to find out if they are supposed to succeed since they are not turned on by default and I see an open issue, https://github.com/ibaned/omega_h/issues/203.

My FEniCS dolfin demos crash at the same point, in the adapt with the above error, in both c++ and Python, I believe though that the problem is general. Any insight is deeply appreciated, thanks.

**Comment by tamaradanceva** [comment]
Finally, I have isolated the problem.. It stems from the function sources_from_destinations (introduced in v9.22.2), commits #fcca41e and  016df15 (Trying to avoid certain MPI things that break on ARM and avoid using newer MPI functions correspondingly). I hope this helps.

**Comment by ibaned** [comment]
@tamaradanceva thanks for identifying this in detail! I pushed 30f2ee8f in an attempt to fix this. Are you able to try the `develop` branch to see if resolves the issue?

**Comment by tamaradanceva** [comment]
@ibaned  Thank you! Yes, now it works.

**Comment by ibaned** [comment]
Thanks again for tracking down the location of the bug!

I just released version `9.24.2` which should be fixed.

Also, please be aware that I intend to move this repository to the following organization within the next few days:
https://github.com/SNLComputation
